// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADHd0IQ80JPsn7QC_O0TaazLcFo4FEkwQ',
    appId: '1:365646558198:web:84d5b7b0ac290c6bbccdd7',
    messagingSenderId: '365646558198',
    projectId: 'flutter-riverpod-grocery-shop',
    authDomain: 'flutter-riverpod-grocery-shop.firebaseapp.com',
    storageBucket: 'flutter-riverpod-grocery-shop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhuZvmjTtKSUQJdM05oUCNuu7ehqTJncg',
    appId: '1:365646558198:android:9cebaa116f4d0e49bccdd7',
    messagingSenderId: '365646558198',
    projectId: 'flutter-riverpod-grocery-shop',
    storageBucket: 'flutter-riverpod-grocery-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXGokc892yRpp44SjkITpCjt1wSrO4tVc',
    appId: '1:365646558198:ios:fde6c83e92eb1d10bccdd7',
    messagingSenderId: '365646558198',
    projectId: 'flutter-riverpod-grocery-shop',
    storageBucket: 'flutter-riverpod-grocery-shop.appspot.com',
    iosBundleId: 'com.example.flutterRiverpodGroceryShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXGokc892yRpp44SjkITpCjt1wSrO4tVc',
    appId: '1:365646558198:ios:f354022d6f50dd55bccdd7',
    messagingSenderId: '365646558198',
    projectId: 'flutter-riverpod-grocery-shop',
    storageBucket: 'flutter-riverpod-grocery-shop.appspot.com',
    iosBundleId: 'com.example.flutterRiverpodGroceryShop.RunnerTests',
  );
}
